

  Exception Analysis
  Exn.res:1:5-10
  raises might throw Not_found (Exn.res:1:19) and is not annotated with @throws(Not_found)

  Exception Analysis
  Exn.res:19:5-28
  callsThrowWithAnnotation might throw Not_found (Exn.res:19:31) and is not annotated with @throws(Not_found)

  Exception Analysis
  Exn.res:22:5-42
  callsThrowWithAnnotationAndIsAnnotated might throw Not_found (Exn.res:22:45) and is not annotated with @throws(Not_found)

  Exception Analysis
  Exn.res:22:5-42
  callsThrowWithAnnotationAndIsAnnotated might throw Not_found (Exn.res:22:45) and is annotated with redundant @throws(A)

  Exception Analysis
  Exn.res:24:5-19
  incompleteMatch might throw Match_failure (Exn.res:25:2) and is not annotated with @throws(Match_failure)

  Exception Analysis
  Exn.res:32:5-13
  twoThrows might throw [A (Exn.res:34:4), B (Exn.res:37:4)] and is not annotated with @throws([A, B])

  Exception Analysis
  Exn.res:41:5-14
  sequencing might throw A (Exn.res:42:2) and is not annotated with @throws(A)

  Exception Analysis
  Exn.res:48:5-14
  wrongCatch might throw B (Exn.res:49:6) and is not annotated with @throws(B)

  Exception Analysis
  Exn.res:54:5-15
  wrongCatch2 might throw [C (Exn.res:55:24), Match_failure (Exn.res:55:2)] and is not annotated with @throws([C, Match_failure])

  Exception Analysis
  Exn.res:62:5-19
  throw2Annotate3 might throw [A (Exn.res:64:4), B (Exn.res:67:4)] and is annotated with redundant @throws(C)

  Exception Analysis
  Exn.res:73:5-24
  parse_json_from_file might throw Error (Exn.res:75:34) and is not annotated with @throws(Error)

  Exception Analysis
  Exn.res:80:5-11
  reThrow might throw B (Exn.res:82:19) and is not annotated with @throws(B)

  Exception Analysis
  Exn.res:91:5-22
  throwInInternalLet might throw A (Exn.res:92:14) and is not annotated with @throws(A)

  Exception Analysis
  Exn.res:96:5-16
  indirectCall might throw Not_found (Exn.res:96:25) and is not annotated with @throws(Not_found)

  Exception Analysis
  Exn.res:121:5-16
  severalCases might throw Failure (Exn.res:123:13 Exn.res:124:13 Exn.res:125:15) and is not annotated with @throws(Failure)

  Exception Analysis
  Exn.res:133:5-23
  redundantAnnotation throws nothing and is annotated with redundant @throws(Invalid_argument)

  Exception Analysis
  Exn.res:135:5-6
  _x might throw A (Exn.res:135:9) and is not annotated with @throws(A)

  Exception Analysis
  Exn.res:137:5
  _ might throw A (Exn.res:137:8) and is not annotated with @throws(A)

  Exception Analysis
  Exn.res:139:5-6
  () might throw A (Exn.res:139:9) and is not annotated with @throws(A)

  Exception Analysis
  Exn.res:141:1-16
  Toplevel expression might throw Not_found (Exn.res:141:0) and is not annotated with @throws(Not_found)

  Exception Analysis
  Exn.res:151:46-47
  expression does not throw and is annotated with redundant @doesNotThrow

  Exception Analysis
  Exn.res:151:5-21
  onResultPipeWrong might throw Assert_failure (Exn.res:151:50) and is not annotated with @throws(Assert_failure)

  Exception Analysis
  ExnA.res:1:5-7
  bar might throw Not_found (ExnA.res:1:16) and is not annotated with @throws(Not_found)

  Exception Analysis
  ExternalTest.res:7:5-24
  bigIntFromStringExn2 might throw JsExn (ExternalTest.res:7:35) and is not annotated with @throws(JsExn)
  
  Analysis reported 24 issues (Exception Analysis:24)
